- name: install docker build-service
  hosts: all
  become: yes
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
#        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
    - name: add GPG_key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: latest
    - name: Install Docker Module for Python
      pip3:
        name: docker
    - name: ensure docker service is started
      service:
        name: docker
        state: started
        enabled: yes

- name: execute docker with build service
  hosts: build
  become: yes
  tasks:
    - name: pull build-service image
      docker_image:
        name: dlmurga/build-service
        source: pull
    - name: create container
      docker_container:
        name: ds-08-build
        state: present

- name: execute docker with tomcat service
  hosts: run
  become: yes
  tasks:
    - name: pull tomcat image
      docker_image:
        name: dlmurga/tomcat-service
        source: pull
    - name: create container
      docker_container:
        name: ds-08-run
        state: present